# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
- package-ecosystem: "devcontainers"
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: "gomod"
  directories:
    - "/modules/buildutils"
    - "/modules/cli"
  schedule:
    interval: daily
- package-ecosystem: "gradle"
  directories:
    - "/modules/platform"
    - "/modules/gradle"
    - "/modules/framework/galasa-parent"
    - "/modules/extensions/galasa-extensions-parent"
    - "/modules/managers/galasa-managers-parent"
  schedule:
    interval: daily
- package-ecosystem: "maven"
  directories:
    - "/modules/wrapping"
    - "/modules/maven/galasa-maven-plugin"
  schedule:
    interval: daily
