#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Gradle PR Build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string

jobs:

  log-unchanged:
    name: Gradle is unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The gradle module is unchanged"

  build-gradle:
    name: Build Gradle source code and Docker image
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            modules/gradle

      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 9.0.0
          gradle-home-cache-excludes: |
            caches/modules-2/files-2.1/dev.galasa/**

      - name: Download platform from this workflow
        id: download-platform
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: modules/artifacts

      - name: Build Gradle source code
        working-directory: modules/gradle
        run: |
          gradle check publish --info \
          --no-daemon --console plain \
          -PsourceMaven=${{ steps.download-platform.outcome == 'success' && format('{0}/modules/artifacts', github.workspace) || 'https://development.galasa.dev/main/maven-repo/obr' }} \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/gradle/repo

      - name: Upload gradle artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle
          path: modules/gradle/repo